---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: uvicorn-deployment
  labels:
    app: uvicorn
spec:
  replicas: 3
  selector:
    matchLabels:
      app: uvicorn
  template:
    metadata:
      labels:
        app: uvicorn
    spec:
      containers:
        - name: uvicorn
          image: python_base-prod:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 5001
          env:
            - name: PORT
              value: "5001"

---
apiVersion: v1
kind: Service
metadata:
  name: uvicorn-service
spec:
  ports:
  - port: 5001
    protocol: TCP
    targetPort: 5001
  selector:
    app: uvicorn
  type: LoadBalancer