# syntax=docker/dockerfile:1
ARG BASE_IMAGE_NAME_ARG
FROM ${BASE_IMAGE_NAME_ARG}

ENV IS_PROD false
ENV IS_DEV true

# install additional dependencies
RUN apt-get update && \
    apt-get install --no-install-recommends -y \
    make \
    unzip \
    git && \
    rm -rf /var/lib/apt/lists/*

# install python and packages
RUN poetry install

# clean up build
WORKDIR /
RUN rm -rf ${BUILD_PATH}