# syntax=docker/dockerfile:1
FROM base_image

ENV IS_PROD false
ENV IS_DEV true

# install additional dependencies
RUN apt-get update && \
    apt-get install --no-install-recommends -y \
    make \
    unzip \
    git && \
    rm -rf /var/lib/apt/lists/*

# install python and packages
RUN poetry install

# clean up build
WORKDIR /
RUN rm -rf ${BUILD_PATH}